name: 🚀 Deploy
on:
  push:
    branches:
      - main
      - 'release/v[0-9]+.[0-9]+'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - 'release/v[0-9]+.[0-9]+'
      - 'main'
  
jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    # needs: [cypress, lint, typecheck, vitest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build
        working-directory: .
        run: |
          npm install
          npm run build

      - name: Unit Test
        working-directory: .
        run: |
          npm run test:unit

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [setup-build-publish]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
